# Generated by Django 3.1.4 on 2021-08-28 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20210827_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='end_line',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='file',
            name='field',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='start_line',
            field=models.IntegerField(default=0),
        ),
    ]
