# Generated by Django 3.1.4 on 2021-08-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20210828_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='end_line',
            field=models.IntegerField(default=0, verbose_name='结束行数'),
        ),
        migrations.AlterField(
            model_name='file',
            name='field',
            field=models.URLField(max_length=255, null=True, verbose_name='文件路径'),
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.CharField(max_length=200, verbose_name='请输入文件名'),
        ),
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False, verbose_name='请输入文件ID'),
        ),
        migrations.AlterField(
            model_name='file',
            name='start_line',
            field=models.IntegerField(default=0, verbose_name='开始行数'),
        ),
    ]
