# Generated by Django 3.1.4 on 2021-08-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210828_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='请输入文件ID'),
        ),
    ]
