# Generated by Django 3.1.4 on 2021-08-30 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210828_1632'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='filename',
            new_name='value',
        ),
    ]
