# Generated by Django 3.1.4 on 2021-08-30 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20210830_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='file',
            old_name='value',
            new_name='name',
        ),
    ]
