# Generated by Django 3.1.4 on 2021-08-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20210830_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='code',
            field=models.CharField(max_length=2000, null=True, verbose_name='请输入代码'),
        ),
    ]
